apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-js-sample
  template:
    metadata:
      labels:
        app: node-js-sample
    spec:
      containers:
      - name: node-js-sample
        image: veerareddy212/node-js-sample:1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: node-js-sample-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: node-js-sample

